CREATE TYPE run_status AS ENUM ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED');
CREATE TYPE run_mode AS ENUM ('FULL_DATASET', 'SAMPLE', 'SELECTED_CASES', 'SELECTED_SECTION', 'FAILED_CASES');

CREATE TABLE runs (
    id                          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id                   UUID            NOT NULL DEFAULT gen_random_uuid(),
    project_id                  BIGINT          NOT NULL,
    dataset_id                  BIGINT          NOT NULL,
    target_id                   BIGINT          NOT NULL,
    status                      run_status      NOT NULL DEFAULT 'PENDING',
    run_mode                    run_mode        NOT NULL DEFAULT 'FULL_DATASET',
    include_llm_judge           BOOLEAN         NOT NULL DEFAULT TRUE,
    include_tool_expectations   BOOLEAN         NOT NULL DEFAULT TRUE,
    max_concurrency             INTEGER         NOT NULL DEFAULT 3,
    timeout_ms                  INTEGER         NOT NULL DEFAULT 30000,
    retry_count                 INTEGER         NOT NULL DEFAULT 0,
    triggered_by                BIGINT,
    previous_run_id             BIGINT,
    selected_case_ids           JSONB           DEFAULT '[]',
    selected_section            VARCHAR(500),
    started_at                  TIMESTAMPTZ,
    finished_at                 TIMESTAMPTZ,
    total_test_cases            INTEGER         NOT NULL DEFAULT 0,
    completed_test_cases        INTEGER         NOT NULL DEFAULT 0,
    passed_count                INTEGER         NOT NULL DEFAULT 0,
    failed_count                INTEGER         NOT NULL DEFAULT 0,
    error_count                 INTEGER         NOT NULL DEFAULT 0,
    skipped_count               INTEGER         NOT NULL DEFAULT 0,
    llm_rubric_count            INTEGER         NOT NULL DEFAULT 0,
    estimated_llm_calls         INTEGER         NOT NULL DEFAULT 0,
    failure_reason              TEXT,
    summary                     JSONB           DEFAULT '{}',
    config_snapshot             JSONB           DEFAULT '{}',
    artifact_path               VARCHAR(1000),
    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_runs_public_id UNIQUE (public_id),
    CONSTRAINT ck_runs_concurrency_range CHECK (max_concurrency >= 1 AND max_concurrency <= 50),
    CONSTRAINT ck_runs_timeout_range CHECK (timeout_ms >= 1000 AND timeout_ms <= 300000),
    CONSTRAINT ck_runs_retry_range CHECK (retry_count >= 0 AND retry_count <= 5),
    CONSTRAINT ck_runs_counter_non_negative CHECK (
        total_test_cases >= 0
        AND completed_test_cases >= 0
        AND passed_count >= 0
        AND failed_count >= 0
        AND error_count >= 0
        AND skipped_count >= 0
        AND llm_rubric_count >= 0
        AND estimated_llm_calls >= 0
    ),
    CONSTRAINT ck_runs_time_order CHECK (
        started_at IS NULL OR finished_at IS NULL OR finished_at >= started_at
    ),
    CONSTRAINT fk_runs_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_runs_dataset FOREIGN KEY (dataset_id) REFERENCES datasets(id) ON DELETE RESTRICT,
    CONSTRAINT fk_runs_target FOREIGN KEY (target_id) REFERENCES targets(id) ON DELETE RESTRICT,
    CONSTRAINT fk_runs_triggered_by FOREIGN KEY (triggered_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_runs_previous_run FOREIGN KEY (previous_run_id) REFERENCES runs(id) ON DELETE SET NULL
);

CREATE INDEX idx_runs_project_id ON runs(project_id);
CREATE INDEX idx_runs_dataset_id ON runs(dataset_id);
CREATE INDEX idx_runs_target_id ON runs(target_id);
CREATE INDEX idx_runs_triggered_by ON runs(triggered_by);
CREATE INDEX idx_runs_status ON runs(status);
CREATE INDEX idx_runs_project_status ON runs(project_id, status);
CREATE INDEX idx_runs_created_at ON runs(created_at DESC);
CREATE INDEX idx_runs_dataset_created ON runs(dataset_id, created_at DESC);
CREATE INDEX idx_runs_previous_run ON runs(previous_run_id) WHERE previous_run_id IS NOT NULL;
CREATE INDEX idx_runs_selected_case_ids ON runs USING GIN (selected_case_ids jsonb_path_ops);
CREATE INDEX idx_runs_config_snapshot ON runs USING GIN (config_snapshot jsonb_path_ops);
