CREATE TABLE manual_reviews (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id           UUID            NOT NULL DEFAULT gen_random_uuid(),
    test_result_id      BIGINT          NOT NULL,
    auto_status         review_status   NOT NULL,
    auto_reason         TEXT,
    reviewed_status     review_status,
    reviewer_note       TEXT,
    reviewed_by         BIGINT,
    reviewed_at         TIMESTAMPTZ,
    final_status        review_status   NOT NULL,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_manual_reviews_public_id UNIQUE (public_id),
    CONSTRAINT uq_manual_reviews_test_result UNIQUE (test_result_id),
    CONSTRAINT ck_manual_reviews_final_status CHECK (
        (reviewed_status IS NOT NULL AND final_status = reviewed_status)
        OR (reviewed_status IS NULL AND final_status = auto_status)
    ),
    CONSTRAINT ck_manual_reviews_review_consistency CHECK (
        (reviewed_status IS NOT NULL AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)
        OR (reviewed_status IS NULL AND reviewed_by IS NULL AND reviewed_at IS NULL)
    ),
    CONSTRAINT fk_manual_reviews_test_result FOREIGN KEY (test_result_id) REFERENCES test_results(id) ON DELETE CASCADE,
    CONSTRAINT fk_manual_reviews_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_manual_reviews_reviewed_by ON manual_reviews(reviewed_by) WHERE reviewed_by IS NOT NULL;
CREATE INDEX idx_manual_reviews_final_status ON manual_reviews(final_status);
CREATE INDEX idx_manual_reviews_pending ON manual_reviews(auto_status)
    WHERE reviewed_status IS NULL AND auto_status IN ('FAILED', 'UNCERTAIN');
CREATE INDEX idx_manual_reviews_reviewed_at ON manual_reviews(reviewed_at DESC) WHERE reviewed_at IS NOT NULL;
