CREATE TABLE projects (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID            NOT NULL DEFAULT gen_random_uuid(),
    name            VARCHAR(255)    NOT NULL,
    description     TEXT,
    owner_id        BIGINT          NOT NULL,
    created_by      BIGINT          NOT NULL,
    archived        BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_projects_public_id UNIQUE (public_id),
    CONSTRAINT uq_projects_name UNIQUE (name),
    CONSTRAINT ck_projects_name_not_empty CHECK (char_length(TRIM(name)) > 0),
    CONSTRAINT fk_projects_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_projects_creator FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
);

-- Owner filter
CREATE INDEX idx_projects_owner_id ON projects (owner_id);

-- Active projects (hide archived)
CREATE INDEX idx_projects_archived ON projects (archived) WHERE archived = FALSE;

-- Sorting/search by name
CREATE INDEX idx_projects_name ON projects (name);

-- Created by filter
CREATE INDEX idx_projects_created_by ON projects (created_by);
