CREATE TYPE target_type AS ENUM ('HTTP', 'LLM');
CREATE TYPE http_method AS ENUM ('GET', 'POST', 'PUT', 'PATCH', 'DELETE');
CREATE TYPE missing_field_behavior AS ENUM ('FAIL', 'SKIP', 'WARNING');

CREATE TABLE targets (
    id                      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id               UUID            NOT NULL DEFAULT gen_random_uuid(),
    project_id              BIGINT          NOT NULL,
    name                    VARCHAR(255)    NOT NULL,
    environment             VARCHAR(50),
    target_type             target_type     NOT NULL DEFAULT 'HTTP',
    
    -- Config cho HTTP Target
    method                  http_method     DEFAULT 'POST',
    url                     TEXT,
    query_params_template   JSONB           DEFAULT '{}',
    headers_template        JSONB           DEFAULT '{}',
    body_template           JSONB           DEFAULT '{}',
    auth_config             JSONB,
    
    -- Config cho LLM Target
    llm_provider            VARCHAR(100),
    llm_model               VARCHAR(100),
    llm_base_url            TEXT,
    llm_key_ref             VARCHAR(255),
    
    -- Binding chung
    input_binding           JSONB,
    variable_bindings       JSONB           DEFAULT '{}',
    timeout_ms              INTEGER         NOT NULL DEFAULT 30000,
    is_default              BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_targets_public_id UNIQUE (public_id),
    CONSTRAINT uq_targets_project_name UNIQUE (project_id, name),
    CONSTRAINT fk_targets_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE response_mappings (
    id                      BIGINT                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_id               BIGINT                  NOT NULL,
    answer_path             VARCHAR(500),
    suggestions_path        VARCHAR(500),
    intent_path             VARCHAR(500),
    confidence_path         VARCHAR(500),
    sources_path            VARCHAR(500),
    retrieval_path          VARCHAR(500),
    memory_path             VARCHAR(500),
    rewrite_path            VARCHAR(500),
    agent_path              VARCHAR(500),
    tool_path               VARCHAR(500),
    tool_calls_path         VARCHAR(500),
    trace_id_path           VARCHAR(500),
    latency_path            VARCHAR(500),
    custom_components       JSONB                   DEFAULT '[]',
    missing_field_behavior  missing_field_behavior  NOT NULL DEFAULT 'FAIL',
    created_at              TIMESTAMPTZ             NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ             NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_response_mappings_target UNIQUE (target_id),
    CONSTRAINT fk_response_mappings_target FOREIGN KEY (target_id) REFERENCES targets(id) ON DELETE CASCADE
);

CREATE INDEX idx_targets_project_id ON targets(project_id);
CREATE INDEX idx_targets_env ON targets(environment);
