CREATE TYPE test_priority AS ENUM ('P0', 'P1', 'P2', 'P3');
CREATE TYPE test_case_source AS ENUM ('MANUAL', 'IMPORTED', 'AI_GENERATED');

CREATE TABLE test_cases (
    id                  BIGINT              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id           UUID                NOT NULL DEFAULT gen_random_uuid(),
    external_id         VARCHAR(255),
    dataset_id          BIGINT              NOT NULL,
    section_name        VARCHAR(500),
    name                VARCHAR(500),
    description         TEXT,
    input               TEXT                NOT NULL,
    expected_behavior   TEXT,
    reference_answer    TEXT,
    variables           JSONB               DEFAULT '{}',
    preconditions       TEXT,
    tags                JSONB               DEFAULT '[]',
    priority            test_priority       NOT NULL DEFAULT 'P2',
    enabled             BOOLEAN             NOT NULL DEFAULT TRUE,
    source              test_case_source    NOT NULL DEFAULT 'MANUAL',
    generated_by        VARCHAR(255),
    generation_prompt   TEXT,
    sort_order          INTEGER             NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ         NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_test_cases_public_id UNIQUE (public_id),
    CONSTRAINT ck_test_cases_input_not_empty CHECK (char_length(TRIM(input)) > 0),
    CONSTRAINT ck_test_cases_sort_order_non_negative CHECK (sort_order >= 0),
    CONSTRAINT fk_test_cases_dataset FOREIGN KEY (dataset_id) REFERENCES datasets(id) ON DELETE CASCADE
);

CREATE INDEX idx_test_cases_dataset_id ON test_cases(dataset_id);
CREATE INDEX idx_test_cases_external_id ON test_cases(external_id) WHERE external_id IS NOT NULL;
CREATE INDEX idx_test_cases_section_name ON test_cases(dataset_id, section_name);
CREATE INDEX idx_test_cases_priority ON test_cases(priority);
CREATE INDEX idx_test_cases_enabled ON test_cases(dataset_id, enabled) WHERE enabled = TRUE;
CREATE INDEX idx_test_cases_source ON test_cases(source);
CREATE INDEX idx_test_cases_sort ON test_cases(dataset_id, sort_order);
CREATE INDEX idx_test_cases_tags ON test_cases USING GIN (tags jsonb_path_ops);
CREATE INDEX idx_test_cases_variables ON test_cases USING GIN (variables jsonb_path_ops);
