CREATE TABLE test_case_import_previews (
    id                      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id               UUID            NOT NULL DEFAULT gen_random_uuid(),
    dataset_id              BIGINT          NOT NULL,
    file_name               VARCHAR(500)    NOT NULL,
    content_type            VARCHAR(255),
    storage_key             VARCHAR(1000)   NOT NULL,
    total_rows              INTEGER         NOT NULL DEFAULT 0,
    detected_columns        JSONB           DEFAULT '[]',
    suggested_mapping       JSONB           DEFAULT '{}',
    sample_rows             JSONB           DEFAULT '[]',
    duplicate_external_ids  JSONB           DEFAULT '[]',
    confirmed               BOOLEAN         NOT NULL DEFAULT FALSE,
    expires_at              TIMESTAMPTZ     NOT NULL,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_test_case_import_previews_public_id UNIQUE (public_id),
    CONSTRAINT fk_test_case_import_previews_dataset FOREIGN KEY (dataset_id) REFERENCES datasets(id) ON DELETE CASCADE,
    CONSTRAINT ck_test_case_import_previews_total_rows CHECK (total_rows >= 0)
);

CREATE INDEX idx_test_case_import_previews_dataset ON test_case_import_previews(dataset_id);
CREATE INDEX idx_test_case_import_previews_expires_at ON test_case_import_previews(expires_at);
