CREATE TYPE rubric_scope AS ENUM ('GLOBAL', 'PROJECT', 'DATASET', 'TESTCASE_OVERRIDE');
CREATE TYPE rubric_category AS ENUM (
    'ANSWER_QUALITY',
    'POLICY_COMPLIANCE',
    'NO_HALLUCINATION',
    'SAFETY_REFUSAL',
    'RAG_FAITHFULNESS',
    'TOOL_OUTPUT_USAGE',
    'SUGGESTION_RELEVANCE',
    'VIETNAMESE_TONE',
    'CLARIFYING_QUESTION',
    'BUSINESS_ACCEPTANCE'
);

CREATE TABLE rubrics (
    id                  BIGINT              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id           UUID                NOT NULL DEFAULT gen_random_uuid(),
    scope               rubric_scope        NOT NULL DEFAULT 'PROJECT',
    project_id          BIGINT,
    dataset_id          BIGINT,
    name                VARCHAR(255)        NOT NULL,
    description         TEXT,
    category            rubric_category     NOT NULL DEFAULT 'ANSWER_QUALITY',
    language            VARCHAR(10)         NOT NULL DEFAULT 'vi',
    content             TEXT                NOT NULL,
    default_threshold   NUMERIC(5,4)        NOT NULL DEFAULT 0.8000,
    metadata            JSONB               DEFAULT '{}',
    created_by          BIGINT,
    archived            BOOLEAN             NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ         NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_rubrics_public_id UNIQUE (public_id),
    CONSTRAINT ck_rubrics_threshold_range CHECK (default_threshold >= 0 AND default_threshold <= 1),
    CONSTRAINT ck_rubrics_content_not_empty CHECK (char_length(TRIM(content)) > 0),
    CONSTRAINT ck_rubrics_scope_consistency CHECK (
        (scope = 'GLOBAL' AND project_id IS NULL AND dataset_id IS NULL)
        OR (scope = 'PROJECT' AND project_id IS NOT NULL AND dataset_id IS NULL)
        OR (scope = 'DATASET' AND project_id IS NOT NULL AND dataset_id IS NOT NULL)
        OR (scope = 'TESTCASE_OVERRIDE' AND project_id IS NOT NULL)
    ),
    CONSTRAINT fk_rubrics_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_rubrics_dataset FOREIGN KEY (dataset_id) REFERENCES datasets(id) ON DELETE CASCADE,
    CONSTRAINT fk_rubrics_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_rubrics_project_id ON rubrics(project_id) WHERE project_id IS NOT NULL;
CREATE INDEX idx_rubrics_dataset_id ON rubrics(dataset_id) WHERE dataset_id IS NOT NULL;
CREATE INDEX idx_rubrics_global ON rubrics(scope) WHERE scope = 'GLOBAL';
CREATE INDEX idx_rubrics_category ON rubrics(category);
CREATE INDEX idx_rubrics_active ON rubrics(archived) WHERE archived = FALSE;
CREATE INDEX idx_rubrics_created_by ON rubrics(created_by);
CREATE INDEX idx_rubrics_project_category ON rubrics(project_id, category, archived) WHERE archived = FALSE;
CREATE INDEX idx_rubrics_metadata ON rubrics USING GIN (metadata jsonb_path_ops);
