CREATE TYPE assertion_scope AS ENUM ('FIELD', 'COMPONENT', 'MULTI_FIELD', 'WHOLE_RESPONSE');
CREATE TYPE assertion_type AS ENUM (
    'contains',
    'not_contains',
    'equals',
    'not_equals',
    'regex',
    'greater_than',
    'less_than',
    'between',
    'is_true',
    'is_false',
    'field_exists',
    'field_not_exists',
    'array_length_greater_than',
    'array_contains',
    'llm_rubric'
);
CREATE TYPE severity_level AS ENUM ('CRITICAL', 'MAJOR', 'MINOR', 'INFO');

CREATE TABLE assertions (
    id                  BIGINT              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id           UUID                NOT NULL DEFAULT gen_random_uuid(),
    test_case_id        BIGINT              NOT NULL,
    scope               assertion_scope     NOT NULL,
    type                assertion_type      NOT NULL,
    target_component    VARCHAR(100),
    field_path          VARCHAR(500),
    field_paths         JSONB               DEFAULT '[]',
    expected_value      JSONB,
    rubric_id           BIGINT,
    rubric_override     TEXT,
    threshold           NUMERIC(5,4)        DEFAULT 0.8000,
    weight              NUMERIC(5,4)        DEFAULT 1.0000,
    severity            severity_level      NOT NULL DEFAULT 'MAJOR',
    enabled             BOOLEAN             NOT NULL DEFAULT TRUE,
    sort_order          INTEGER             NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ         NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_assertions_public_id UNIQUE (public_id),
    CONSTRAINT ck_assertions_threshold_range CHECK (threshold IS NULL OR (threshold >= 0 AND threshold <= 1)),
    CONSTRAINT ck_assertions_weight_positive CHECK (weight IS NULL OR weight > 0),
    CONSTRAINT ck_assertions_sort_order_non_negative CHECK (sort_order >= 0),
    CONSTRAINT ck_assertions_scope_field CHECK (
        (scope = 'FIELD' AND field_path IS NOT NULL)
        OR (scope = 'COMPONENT' AND target_component IS NOT NULL)
        OR (scope = 'MULTI_FIELD' AND field_paths IS NOT NULL AND jsonb_array_length(field_paths) > 0)
        OR (scope = 'WHOLE_RESPONSE')
    ),
    CONSTRAINT fk_assertions_test_case FOREIGN KEY (test_case_id) REFERENCES test_cases(id) ON DELETE CASCADE,
    CONSTRAINT fk_assertions_rubric FOREIGN KEY (rubric_id) REFERENCES rubrics(id) ON DELETE SET NULL
);

CREATE INDEX idx_assertions_test_case_id ON assertions(test_case_id);
CREATE INDEX idx_assertions_rubric_id ON assertions(rubric_id) WHERE rubric_id IS NOT NULL;
CREATE INDEX idx_assertions_scope_type ON assertions(scope, type);
CREATE INDEX idx_assertions_severity ON assertions(severity);
CREATE INDEX idx_assertions_enabled ON assertions(test_case_id, enabled) WHERE enabled = TRUE;
CREATE INDEX idx_assertions_field_paths ON assertions USING GIN (field_paths jsonb_path_ops);
CREATE INDEX idx_assertions_expected_value ON assertions USING GIN (expected_value jsonb_path_ops);
