CREATE TYPE tool_expectation_type AS ENUM (
    'TOOL_MUST_BE_CALLED',
    'TOOL_MUST_NOT_BE_CALLED',
    'TOOL_ARGS_MATCH',
    'TOOL_SEQUENCE_MATCH',
    'TOOL_CALL_COUNT',
    'TOOL_OUTPUT_USED_IN_ANSWER',
    'AGENT_EQUALS',
    'AGENT_NOT_EQUALS',
    'AGENT_STEP_CONTAINS'
);
CREATE TYPE target_source_type AS ENUM (
    'normalized_tool_calls',
    'inferred_tool',
    'inferred_agent',
    'agent_steps',
    'trace',
    'custom_component'
);

CREATE TABLE tool_expectations (
    id                    BIGINT                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id             UUID                    NOT NULL DEFAULT gen_random_uuid(),
    test_case_id          BIGINT                  NOT NULL,
    expectation_type      tool_expectation_type   NOT NULL,
    target_source         target_source_type      NOT NULL DEFAULT 'normalized_tool_calls',
    tool_name             VARCHAR(255),
    agent_name            VARCHAR(255),
    argument_assertions   JSONB                   DEFAULT '[]',
    sequence              JSONB                   DEFAULT '[]',
    min_calls             INTEGER,
    max_calls             INTEGER,
    rubric_id             BIGINT,
    rubric_override       TEXT,
    threshold             NUMERIC(5,4)            DEFAULT 0.8000,
    required              BOOLEAN                 NOT NULL DEFAULT TRUE,
    severity              severity_level          NOT NULL DEFAULT 'MAJOR',
    enabled               BOOLEAN                 NOT NULL DEFAULT TRUE,
    sort_order            INTEGER                 NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ             NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ             NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_tool_exp_public_id UNIQUE (public_id),
    CONSTRAINT ck_tool_exp_threshold_range CHECK (threshold IS NULL OR (threshold >= 0 AND threshold <= 1)),
    CONSTRAINT ck_tool_exp_call_count CHECK (min_calls IS NULL OR max_calls IS NULL OR min_calls <= max_calls),
    CONSTRAINT ck_tool_exp_min_calls_positive CHECK (min_calls IS NULL OR min_calls >= 0),
    CONSTRAINT ck_tool_exp_max_calls_positive CHECK (max_calls IS NULL OR max_calls >= 0),
    CONSTRAINT ck_tool_exp_sort_order_non_negative CHECK (sort_order >= 0),
    CONSTRAINT fk_tool_exp_test_case FOREIGN KEY (test_case_id) REFERENCES test_cases(id) ON DELETE CASCADE,
    CONSTRAINT fk_tool_exp_rubric FOREIGN KEY (rubric_id) REFERENCES rubrics(id) ON DELETE SET NULL
);

CREATE INDEX idx_tool_exp_test_case_id ON tool_expectations(test_case_id);
CREATE INDEX idx_tool_exp_rubric_id ON tool_expectations(rubric_id) WHERE rubric_id IS NOT NULL;
CREATE INDEX idx_tool_exp_type ON tool_expectations(expectation_type);
CREATE INDEX idx_tool_exp_tool_name ON tool_expectations(tool_name) WHERE tool_name IS NOT NULL;
CREATE INDEX idx_tool_exp_enabled ON tool_expectations(test_case_id, enabled) WHERE enabled = TRUE;
CREATE INDEX idx_tool_exp_argument_assertions ON tool_expectations USING GIN (argument_assertions jsonb_path_ops);
CREATE INDEX idx_tool_exp_sequence ON tool_expectations USING GIN (sequence jsonb_path_ops);
